### PR TITLE
Pre-commit and code cleanup

### LINKED ISSUE #11: Code cleanup and pre-commit hooks
The repository misses pre-commit hooks. The code needs a proper cleanup.

### PR DESCRIPTION
**Pull request by neodark**
This PR makes sure previous submitted code and all future contributors will respect strict formatting automatically.

* When a git commit is done it will re-format if needed and contributors need to do a git add with proposed modifications.
* It re-orders the imports
* It makes sure people who submit code don't submit unused libraries and variables before submitting

Added hooks and did some code cleanup to make the package easier to maintain

Closes #11

### CODE REVIEW

**Comment by neodark** [comment]
Here it makes sense to remove the warning related to E501 as this was already not respected before you installed `pep8speaks`. Usually this could be ignored even when using `flake8` (warning removed there too) 

Note: do you mind adding the tag `hacktoberfest-accepted` when merging this PR ?

**Comment by Holmes7** [comment]
Awesome work @neodark 
I think this will be a great addition to the repo.
@rakaar I think adding the description of the PR in README would be nice and would like to request neodark to add it. What do you think?
Also please look at the .flake8 file and check if the configuration is alright.
Other than that I think we are good to go.
Lastly we are sorry that it took so long to review the PR

**Comment by neodark** [comment]
@Holmes7 , @rakaar : thanks for your comments :+1: 

Actually I already added them in the README.md in my PR:
- pip install -r requirements.txt
- pre-commit install

As I included all libraries in the `requirements.txt` and basically this extra line `pre-commit install` that the user should do would install that.

We can therefore guarantee that they can commit only well formatted code. As they locally get already errors during development that needs to be corrected.
Could you clarify what other things you want definition you wish me to add to the `README` file ?

No problem for the delay :wink:

**Comment by Holmes7** [comment]
@neodark I was talking about adding the three bullet points of this PR in README Scripts section just so that people know what it does. Add those and we will merge the PR. Once again thank you for the work

**Comment by rakaar** [comment]
>generate_statistics.py needs a re-write.

thanks for mentioning this, we actually plan to improve the code by including concurrency. Will open an issue soon.

**Comment by neodark** [comment]
@Holmes7 @rakaar : 

As requested, you will now find the modified `README.md` file. I thought it would be better to add a new section with more details instead of just the 3 bullet points mentioned above here (this helps to make sure the process is understood by contributors).

Yes I feel that `generate_statistics.py` is over complicated and code should really be improved there. However I don't understand why you need to include concurrency here ? Could you elaborate a bit ? Why do you need to handle that ?

You're welcome with the provided work. It was a pleasure contributing to this package. I might contribute to it even after the `hacktoberfest` if you don't mind having other PR and contributions from my side?

**Comment by Holmes7** [comment]
@neodark Thanks a lot for your work.

**Comment by rakaar** [comment]
>Yes I feel that generate_statistics.py is over complicated and code should really be improved there. However I don't understand why you need to include concurrency here ? Could you elaborate a bit ? Why do you need to handle that ?

the purpose of `generate_statistics.py` is to generate statistics of all students participating in KWoC. It takes around 15 minutes to generate new statistics completely. Hence I was expecting that concurrency would help to speed that up. We can also using multiprocessing. But again u have to use a  shared memory to put all the statistics at one place. I will open a issue soon. Currently, I am not opening it because, there are already 3 PRs, which we are unable to "manage" due to the current load. It would be really bad on our part and frustrating to contributors if their PRs keep hanging. Once few PRs are merged, the issue will be created. If you willing to work and try it out, feel free to send a PR.

>You're welcome with the provided work. It was a pleasure contributing to this package. I might contribute to it even after the hacktoberfest if you don't mind having other PR and contributions from my side?

Thank you so much for these words. So kind of you!
Showing students' and projects' statistics are a very important part of KWoC as evaluations depend on them. Your contributions to the package will have a great impact to the community
Thank you once again

**Pull request merged**
