### PR TITLE
Added sheet.py to repo, updated requirements.txt

### PR DESCRIPTION
**Pull request by AlejandroGomezFrieiro**
Added a python script sheet.py that, given Google API credentials and an email address, creates a sheet and populates it with students_.csv

This solves Issue #5

### CODE REVIEW

**Comment by rakaar** [comment]
Hey @AlejandroGomezFrieiro 
Thank you for the PR!


I have a small request, sorry to tell you that this late.
Can you add another column that goes by name `feedback` in the google sheet.

**Comment by Holmes7** [comment]
Thanks for the PR @AlejandroGomezFrieiro 
It is giving me an error on the create function probably because I made some mistake when creating the credentials but I just wanted to check if is working for you.

**Comment by AlejandroGomezFrieiro** [comment]
> Thanks for the PR @AlejandroGomezFrieiro
> It is giving me an error on the create function probably because I made some mistake when creating the credentials but I just wanted to check if is working for you.

It works for me, as long as the API is set properly following the link on the script.

**Comment by AlejandroGomezFrieiro** [comment]
> Hey @AlejandroGomezFrieiro
> Thank you for the PR!
> 
> I have a small request, sorry to tell you that this late.
> Can you add another column that goes by name `feedback` in the google sheet.

Added a new column to the worksheet as wanted

**Comment by rakaar** [comment]
Hey @AlejandroGomezFrieiro 
sorry for the delay 
it is giving me this error
image

On some googling, it says [scope needs to updated](https://github.com/burnash/gspread/issues/513). Can you please update the scope if that is necessary.

Just to make sure both of us are on same page
I followed [these](https://gspread.readthedocs.io/en/latest/oauth2.html#enable-api-access) instructions
```
Enable API Access for a Project if you haven’t done it yet.
Go to “APIs & Services > Credentials” and choose “Create credentials > Service account key”.
Fill out the form
Click “Create key”
Select “JSON” and click “Create”
```
And enabled Google Sheets API and Google drive API for the project created in google console

**Pull request closed without merging**
