### PR TITLE
Identify no commits users and generate csv file

### LINKED ISSUE #4: A script to generate a CSV of people with no commits
In a new file,
write a python script, which uses this [JSON file](https://github.com/kossiitkgp/kwoc-stats-api/blob/master/stats.json) and generate a new CSV file with columns -`Name`, `Email` of the students with 0 commits.

For the Emails
One needs need to iterate through rows of the [CSV file](https://github.com/kossiitkgp/kwoc-stats-api/blob/master/students_.csv)
and find the email of the student,
It is recommended that u search for email in the CSV using handle, which is guarenteed to be unique rather than name which can sometimes be similar

### PR DESCRIPTION
**Pull request by neodark**
This code loads a json file and generates a csv file with the name and affiliation of users that have no commits

Closes #4

### CODE REVIEW

**Comment by Holmes7** [comment]
I locally tested this and it works. @rakaar Please clarify his doubt regarding email address mentioned in issue #4

**Comment by rakaar** [comment]
@neodark @Holmes7 
addressed that in the #4 
sorry for not mentioning that before

**Comment by neodark** [comment]
Thanks to both of your for your comments.
Here the code has been updated to reflect that. Now all should be working fine.

**Review by rakaar — APPROVED** [review]
Its great!

I have a last request from my side.
It would be nice if u can mention at the top of the file - what it does exactly like `Generate a CSV with name and email of students with No commits`.
And correspondingly in README.md add a section named `Scripts`. And under it write a line on what this script does. 

REASON  - We want this API to be maintained for a long time. It will be easy if things are documented

**Comment by neodark** [comment]
Sure will add that.

**Comment by neodark** [comment]
Here it is :slightly_smiling_face: 
`README.md` and script have been updated

**Pull request merged**
